# Generated by Gemini AI
#
#make sure perf in installed before running this script
#
#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <PID> <INTERVAL_SECONDS> <DURATION_SECONDS>"
    echo "Example: $0 34265 10 60"
    exit 1
fi

PID=$1
INTERVAL=$2
DURATION=$3
END_TIME=$((SECONDS + DURATION))

if ! kill -0 "$PID" 2>/dev/null; then
    echo "Error: Process ID $PID does not exist."
    exit 1
fi

# Print clean CSV Header
echo "Timestamp,Cycles,Instructions,IPC"

while [ $SECONDS -lt $END_TIME ]; do
    if ! kill -0 "$PID" 2>/dev/null; then
        echo "$(date '+%Y-%m-%d %H:%M:%S'),0,0,0.00"
        exit 0
    fi

    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

    # Run perf stat, capture stderr (2>&1), and clean up formatting
    # Commas within long numbers are stripped out to keep the CSV clean
    perf stat -e cycles,instructions -p "$PID" -- sleep "$INTERVAL" 2>&1 | awk -v ts="$TIMESTAMP" '
        # Clean up commas out of big numeric values for formatting safety
        { gsub(/,/, "", $1) }
        
        # Match lines by checking the string text in column 2
        $2 == "cycles"       { cycles = $1 }
        $2 == "instructions" { instructions = $1; ipc = $4 }
        
        END {
            # Provide fallbacks if the host blocks PMU register access
            if (!cycles) cycles = 0
            if (!instructions) instructions = 0
            if (!ipc || ipc == "#") ipc = "0.00"
            
            printf "%s,%s,%s,%s\n", ts, cycles, instructions, ipc
        }
    '
done
