# Generated by Gemini AI
#
# dnf install perf numactl -y
#!/bin/bash

# Default flags set to disabled
COLLECT_NUMA=false
COLLECT_PERF=false

# Print usage instructions
usage() {
    echo "Usage: $0 -p <PID> -i <INTERVAL> -d <DURATION> [--numa] [--perf]"
    echo "Example (Both): $0 -p 34265 -i 10 -d 60 --numa --perf"
    echo "Example (NUMA only): $0 -p 34265 -i 10 -d 60 --numa"
    exit 1
}

# Parse command line inputs
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -p) PID="$2"; shift 2 ;;
        -i) INTERVAL="$2"; shift 2 ;;
        -d) DURATION="$2"; shift 2 ;;
        --numa) COLLECT_NUMA=true; shift ;;
        --perf) COLLECT_PERF=true; shift ;;
        *) usage ;;
    esac
done

# Validate required tracking inputs
if [ -z "$PID" ] || [ -z "$INTERVAL" ] || [ -z "$DURATION" ]; then
    usage
fi

if [ "$COLLECT_NUMA" = false ] && [ "$COLLECT_PERF" = false ]; then
    echo "Error: You must specify at least one metric flag (--numa or --perf)."
    usage
fi

if ! kill -0 "$PID" 2>/dev/null; then
    echo "Error: Process ID $PID does not exist."
    exit 1
fi

# Tool availability checks
HAS_NUMA=false
HAS_PERF=false

if [ "$COLLECT_NUMA" = true ]; then
    if command -v numastat &> /dev/null; then
        HAS_NUMA=true
    else
        echo "Warning: 'numastat' command not found. NUMA fields will output as 0.00." >&2
    fi
fi

if [ "$COLLECT_PERF" = true ]; then
    if command -v perf &> /dev/null; then
        HAS_PERF=true
    else
        echo "Warning: 'perf' command not found. Perf fields will output as 0." >&2
    fi
fi

# Build and print the master CSV Header
HEADER="Timestamp"
[ "$COLLECT_NUMA" = true ] && HEADER+=",Node0_Huge_MB,Node0_Heap_MB,Node0_Stack_MB,Node0_Private_MB,Node0_Total_MB,Node1_Huge_MB,Node1_Heap_MB,Node1_Stack_MB,Node1_Private_MB,Node1_Total_MB,Total_Huge_MB,Total_Heap_MB,Total_Stack_MB,Total_Private_MB,Total_Total_MB"
[ "$COLLECT_PERF" = true ] && HEADER+=",Cycles,Instructions,IPC"
echo "$HEADER"

END_TIME=$((SECONDS + DURATION))

# Start metric collection loop
while [ $SECONDS -lt $END_TIME ]; do
    if ! kill -0 "$PID" 2>/dev/null; then
        # Handle mid-run process exits cleanly
        DEAD_ROW="$(date '+%Y-%m-%d %H:%M:%S')"
        [ "$COLLECT_NUMA" = true ] && DEAD_ROW+=",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
        [ "$COLLECT_PERF" = true ] && DEAD_ROW+=",0,0,0.00"
        echo "$DEAD_ROW"
        exit 0
    fi

    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    ROW_DATA="$TIMESTAMP"

    # 1. Gather and flatten NUMA statistics
    if [ "$COLLECT_NUMA" = true ]; then
        if [ "$HAS_NUMA" = true ]; then
            NUMA_OUT=$(numastat -p "$PID" | awk '
                /Node/ { 
                    idx = 1
                    for (i = 1; i <= NF; i++) {
                        if ($i == "Node") { idx++; nodes[idx] = "node" $(i+1); i++ }
                        else if ($i == "Total") { idx++; nodes[idx] = "total" }
                    }
                    next
                }
                /^Huge/    { for(i=2; i<=NF; i++) huge[i]=$i }
                /^Heap/    { for(i=2; i<=NF; i++) heap[i]=$i }
                /^Stack/   { for(i=2; i<=NF; i++) stack[i]=$i }
                /^Private/ { for(i=2; i<=NF; i++) private[i]=$i }
                /^Total/   { for(i=2; i<=NF; i++) total[i]=$i }
                END {
                    printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s",
                        huge[2]?huge[2]:"0.00", heap[2]?heap[2]:"0.00", stack[2]?stack[2]:"0.00", private[2]?private[2]:"0.00", total[2]?total[2]:"0.00",
                        huge[3]?huge[3]:"0.00", heap[3]?heap[3]:"0.00", stack[3]?stack[3]:"0.00", private[3]?private[3]:"0.00", total[3]?total[3]:"0.00",
                        huge[4]?huge[4]:"0.00", heap[4]?heap[4]:"0.00", stack[4]?stack[4]:"0.00", private[4]?private[4]:"0.00", total[4]?total[4]:"0.00"
                }
            ')
        else
            NUMA_OUT="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00"
        fi
        ROW_DATA+=",$NUMA_OUT"
    fi

    # 2. Gather and flatten Perf hardware statistics
    if [ "$COLLECT_PERF" = true ]; then
        if [ "$HAS_PERF" = true ]; then
            PERF_OUT=$(perf stat -e cycles,instructions -p "$PID" -- sleep "$INTERVAL" 2>&1 | awk '
                { gsub(/,/, "", $1) }
                $2 == "cycles"       { cycles = $1 }
                $2 == "instructions" { instructions = $1; ipc = $4 }
                END {
                    if (!cycles) cycles = 0
                    if (!instructions) instructions = 0
                    if (!ipc || ipc == "#") ipc = "0.00"
                    printf "%s,%s,%s", cycles, instructions, ipc
                }
            ')
        else
            PERF_OUT="0,0,0.00"
            sleep "$INTERVAL" # Maintain interval timing if perf is offline
        fi
        ROW_DATA+=",$PERF_OUT"
    else
        sleep "$INTERVAL" # Maintain interval timing if perf tracking is skipped
    fi

    echo "$ROW_DATA"
done
