# Generated by Gemini AI
#
#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <PID> <INTERVAL_SECONDS> <DURATION_SECONDS>"
    echo "Example: $0 34265 10 60"
    exit 1
fi

PID=$1
INTERVAL=$2
DURATION=$3
END_TIME=$((SECONDS + DURATION))

if ! kill -0 "$PID" 2>/dev/null; then
    echo "Error: Process ID $PID does not exist."
    exit 1
fi

# Print a flat single-row CSV Header
echo "Timestamp,Node0_Huge_MB,Node0_Heap_MB,Node0_Stack_MB,Node0_Private_MB,Node0_Total_MB,Node1_Huge_MB,Node1_Heap_MB,Node1_Stack_MB,Node1_Private_MB,Node1_Total_MB,Total_Huge_MB,Total_Heap_MB,Total_Stack_MB,Total_Private_MB,Total_Total_MB"

while [ $SECONDS -lt $END_TIME ]; do
    if ! kill -0 "$PID" 2>/dev/null; then
        # Fill row with zeros if the process exits mid-run
        echo "$(date '+%Y-%m-%d %H:%M:%S'),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
        exit 0
    fi

    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

    # Pass the data through awk to merge the nodes horizontally
    numastat -p "$PID" | awk -v ts="$TIMESTAMP" '
        # Capture column mappings dynamically (Node 0 is index 2, Node 1 is index 3, Total is index 4)
        /Node/ { 
            idx = 1
            for (i = 1; i <= NF; i++) {
                if ($i == "Node") { idx++; nodes[idx] = "node" $(i+1); i++ }
                else if ($i == "Total") { idx++; nodes[idx] = "total" }
            }
            next
        }
        
        # Populate matrices matching rows
        /^Huge/    { for(i=2; i<=NF; i++) huge[i]=$i }
        /^Heap/    { for(i=2; i<=NF; i++) heap[i]=$i }
        /^Stack/   { for(i=2; i<=NF; i++) stack[i]=$i }
        /^Private/ { for(i=2; i<=NF; i++) private[i]=$i }
        /^Total/   { for(i=2; i<=NF; i++) total[i]=$i }
        
        END {
            # Explicitly print the columns side-by-side for Node 0 (col 2), Node 1 (col 3), and Total (col 4)
            # Fall back to "0.00" if a certain column doesn'\''t exist or is empty
            printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n", ts,
                huge[2]?huge[2]:"0.00", heap[2]?heap[2]:"0.00", stack[2]?stack[2]:"0.00", private[2]?private[2]:"0.00", total[2]?total[2]:"0.00",
                huge[3]?huge[3]:"0.00", heap[3]?heap[3]:"0.00", stack[3]?stack[3]:"0.00", private[3]?private[3]:"0.00", total[3]?total[3]:"0.00",
                huge[4]?huge[4]:"0.00", heap[4]?heap[4]:"0.00", stack[4]?stack[4]:"0.00", private[4]?private[4]:"0.00", total[4]?total[4]:"0.00"
        }
    '

    sleep "$INTERVAL"
done
